In [1]:
# Numpy is the foundation for most analytical packages

In [2]:
# its data structures are faster and take up less memory than built in

In [3]:
# allows for complex operations without needing a for loop

In [69]:
import numpy as np

In [70]:
my_arr = np.arange(1000000)

In [6]:
L = list(range(1000000))

In [7]:
# it has an Ndimensional array object

In [8]:
# example

In [9]:
data = np.random.randn(2,3)

In [10]:
data

array([[ 1.2153711 ,  1.32373597,  0.00533156],
       [ 0.50610439, -1.08781649,  0.5207655 ]])

In [11]:
data*2

array([[ 2.43074219,  2.64747193,  0.01066311],
       [ 1.01220879, -2.17563298,  1.04153099]])

In [12]:
data + data

array([[ 2.43074219,  2.64747193,  0.01066311],
       [ 1.01220879, -2.17563298,  1.04153099]])

In [13]:
# like a matrix the data mist be of the same type

In [14]:
# narray has a dimension called shape and dtype the type of data

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

In [17]:
x = [6,7.5,8,0,1]

In [22]:
A = np.array(x)

In [23]:
A

array([6. , 7.5, 8. , 0. , 1. ])

In [24]:
# nested sequences will be converted to multi row arrays

In [25]:
x2 = [[1,2,3],[4,5,6]]

In [26]:
x2

[[1, 2, 3], [4, 5, 6]]

In [27]:
A2 = np.array(x2)

In [28]:
A2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
A2.ndim

2

In [30]:
A2.shape

(2, 3)

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
# you can create arrays of 0 or 1

In [33]:
np.zeros

<function numpy.core.multiarray.zeros>

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
# can also create an empty array

In [37]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
# you can specify rows, columns
np.zeros((10,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
# notes the need for a double parenthesis

In [42]:
# np.arange is different version of range function. probably faster

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# a list of functions

In [46]:
# array - create an array

In [47]:
# asarray convert type to array

In [48]:
# ones / ones_like - produce 1's arrays

In [49]:
# empty / empty_like - same thing for empty

In [50]:
# full / full_like - same thing but you input the value you want

In [51]:
# eye / identity - create an identity square matrix

In [53]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [56]:
np.full((10,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [57]:
# there is more flexibility over the data types but this is more for later

In [58]:
# you can convert types using astype

In [59]:
X = np.full((10,3),5)

In [60]:
X

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [62]:
X.astype(np.string_)

array([[b'5', b'5', b'5'],
       [b'5', b'5', b'5'],
       [b'5', b'5', b'5'],
       [b'5', b'5', b'5'],
       [b'5', b'5', b'5'],
       [b'5', b'5', b'5'],
       [b'5', b'5', b'5'],
       [b'5', b'5', b'5'],
       [b'5', b'5', b'5'],
       [b'5', b'5', b'5']], dtype='|S21')

In [63]:
# doesn't seem right. Why is this?

In [64]:
# astype always creates a new copy of the data

In [65]:
# you can also assign the data type as you are creating the array

In [3]:
array = np.array

In [5]:
X=array([.22,3,.454,78],dtype = np.string_)

In [6]:
X

array([b'0.22', b'3', b'0.454', b'78'], dtype='|S5')

In [7]:
# for astype you can also use the X.dtype as in X2.astype(X1.dtype)

In [8]:
# operations - arrays can be added and subtracted they could be multiplied, raised to power, divided

In [9]:
# you can also get a vector of logicals with comparisons

In [10]:
X1 = array([1,6,3])

In [11]:
X2 = array([3,8,1])

In [12]:
X1 > X2

array([False, False,  True])

In [13]:
X1 == X2

array([False, False, False])

In [14]:
# INDEXING

In [15]:
# for simplicity lets start with a one dimensional array

In [17]:
# converting functions
arange = np.arange;

In [18]:
X = arange(10)

In [19]:
X[3]

3

In [20]:
X[5:8]

array([5, 6, 7])

In [21]:
X[5:8] = 12

In [22]:
X

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [23]:
X[5:8] = [5,6,7]

In [24]:
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
X[5:8] = array([43243,43535,7.1])

In [28]:
X

array([    0,     1,     2,     3,     4, 43243, 43535,     7,     8,
           9])

In [29]:
# note that it originally decided for the data type not to be able to store large numbers

In [30]:
# then if you put in decimals it will convert them to integers

In [31]:
X[:] = 64

In [32]:
X

array([64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [33]:
# essentially the : assigns to every value

In [34]:
# TWO DIMENSIONAL ARRAYS

In [41]:
X = array([ [1,2,3],[4,5,6],[7,8,9] ] ); X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
X[1,2]

6

In [47]:
X[1][2]

6

In [49]:
X[0]

array([1, 2, 3])

In [50]:
# copying a subset of values

In [63]:
X_copy = X[0].copy()

In [64]:
X_copy

array([1, 2, 3])

In [65]:
X[0] = [23432,43,34]

In [66]:
X 

array([[23432,    43,    34],
       [    4,     5,     6],
       [    7,     8,     9]])

In [67]:
X[0] = X_copy

In [68]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
# assignment doesn't work the same way as in R you need the copy

In [70]:
# NOTE THAT I STOPED AT INDEXING WITH SLICES CH4